version: '3.4'

services:
  samba:
    image: elswork/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped
    volumes:
      - /home/${USERNAME}/trans-movie:/share/folder
      #- /path/to/be/shared:/share/folder
    command: '-u "1002:1002:${USERNAME}:${USERNAME}:32502310" -s "mount:/share/folder:rw:${USERNAME}"'
    # command: '-u "uid:guid:username:groupname:put-any-password-here" -s "SmbShare:/share/folder:rw:username"'

# networks:
  # default:
