---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= beellz
      - PASS= 32502310
      - WHITELIST= "127.0.0.1,*.*.*.*"
      - PEERPORT= #optional
      - HOST_WHITELIST= "*"
    volumes:
      - /home/beellz/trans-movie/config:/config
      - /home/beellz/trans-movie/download:/downloads
      - /home/beellz/trans-movie/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
